### ISSUE TITLE
pycountry bug in recent version

### ISSUE THREAD

**Issue by joker234** [mfherbst/down-frab-videos#14]
@pseyfert and I detected a bug regarding the recent `pycountry` in version `18.12.8`. If I install an older version, using `pip3 install "pycountry==18.5.26"` everything works fine.

With `18.12.8`:
```bash
$ down-frab-videos 9744                                         
#######################################
#-- Gathering lecture data for 35c3 --#
#######################################
 - Media file information from "cdn.media.ccc.de" for the formats:
    - webm-hd
Traceback (most recent call last):
  File "/home/user/.local/bin/down-frab-videos", line 4, in <module>
    main()
  File "/home/user/.local/lib/python3.7/site-packages/down_frab_videos/__init__.py", line 1055, in main
    raise_on_error=args.strict))
  File "/home/user/.local/lib/python3.7/site-packages/down_frab_videos/__init__.py", line 195, in __init__
    self.__parse_link(hreftext, self.cached)
  File "/home/user/.local/lib/python3.7/site-packages/down_frab_videos/__init__.py", line 346, in __parse_link
    languages = media_url_builder.__parse_languages(link, splitted)
  File "/home/user/.local/lib/python3.7/site-packages/down_frab_videos/__init__.py", line 297, in __parse_languages
    languages.add(getattr(langobject, lang_outkey))
AttributeError: 'NoneType' object has no attribute 'alpha_3'
```

With `18.5.26`:
```bash
$ down-frab-videos 9744 
#######################################
#-- Gathering lecture data for 35c3 --#
#######################################
 - Media file information from "cdn.media.ccc.de" for the formats:
    - webm-hd
      ... skipping "35c3-9904-eng-deu-chi-The_Social_Credit_System_webm-hd.webm" (invalid language code)

      Note: The skipped files could not be parsed and will not be available
            for download. Either patch this script or download them manually.

 - Fahrplan from "fahrplan.events.ccc.de".
 - Finished: Got "35th Chaos Communication Congress", version "Love Boat"

Saving an error log to the file "errors".

############
#-- 9744 --#
############
[…]
```

**Comment by mfherbst** [comment]
Thanks for the report. I'll take a look into it.

**Comment by mfherbst** [comment]
Fixed by 4bee4c5ad4e8ea4f9f3a0ed1333bbc54ced28317 on my machine. Could you please verify current master works for you as well?

**Comment by pseyfert** [comment]
the fix works for me

**Comment by pseyfert** [comment]
FYI we got a pointer to [this](https://github.com/voc/voctoweb/blob/master/lib/languages.rb) concerning the language codes.

**Comment by mfherbst** [comment]
Great. Thanks ... that's a bit yikes. I thought the would adhere to some kind of standard. Turns out it's their own ;). But if one uses the table you reference it will allow to make `down-frab-videos` more reliable and remove a lot of hackery.

**Comment by mfherbst** [comment]
Closing this for now.

**Comment by joker234** [comment]
> FYI we got a pointer to [this](https://github.com/voc/voctoweb/blob/master/lib/languages.rb) concerning the language codes.

FYI: I got in touch with voc and want to figure out if they will use one standard instead of multiple one or their own.

**Comment by mfherbst** [comment]
Cool. Thanks.

**Comment by mfherbst** [comment]
Related to #16
